services:
  - type: web
    name: motherlode-cmms-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1

  - type: static_site
    name: motherlode-cmms-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: "dist"
    routes:
      # Replace <your-backend-subdomain> after backend finishes its first deploy.
      - type: rewrite
        source: /api/*
        destination: https://<your-backend-subdomain>.onrender.com/api/$1
      - type: rewrite
        source: /uploads/*
        destination: https://<your-backend-subdomain>.onrender.com/uploads/$1
